### ISSUE TITLE
[qnxlab] lab1

### ISSUE THREAD

**Issue by 146karol** [ztmir/ztmir-texfactory#56]
W instrukcji do laboratorium 1, w przykładzie 1.6.9 [Sekwencja warunkowa-alternatywa] w miejscu linii 5 powinno być, moim zdaniem, napis ,,Znaleziono".

Z tego co rozumiem:
1. Polecenie cat odczytuje plik piszA, który zgodnie z treścią instrukcji powinien mieć treść ,,echo ”Zmienna A: ” $A".
2. Poprzez potok dane te są przekazywane do polecenia grep, który szuka:
a) w linii 1 napisu ,,A" i go znajduje, oznacza to, że polecenie [echo "Znaleziono"] nie zostanie wykonane, a zmienna $? przyjmie wartość 0.
b) w linii 4 napisu ,,kawa", którego nie znajduje, więc, wg. mnie, powinien wywołac polecenie  [echo "Znaleziono"], a zmienna $? przyjmie wartość 0, jednak moim zdaniem w wierszu 5 powinien zlaeźć się wynik wywołanego polecenia znaleziono.

Wg. mnie analogicznie mogłoby być w wierszu 2 przykładu 1.6.8

**Comment by ptomulik** [comment]
Zgadza się. Ten przykład trzeba poprawić. Komunikaty też są mylące, należałoby je zmienić na "Nie znaleziono". Poza tym, grep samo w sobie też czasami coś wypisuje na ekran i tego nie widać w przykładzie. Dziękujemy za zgłoszenie.

**Comment by ptomulik** [comment]
Odpowiednia poprawka w #57, zamykam case.
