### ISSUE TITLE
[qnx][lab 4] Przykład 4.3.2.

### ISSUE THREAD

**Issue by 146karol** [ztmir/ztmir-texfactory#62]
Proszę o rozważenie zmiany w przykładzie 4.3.2.

w if (child_pid != )
{
...
printf("M: Proces macierzysty o PID=%d zakonczony\n", child_pid);
}
Zmienna child_pid przechowuje PID procesu potomnego, natomiast treść komunikatu sugeruje zakończenie procesu macierzystego. Warto zwrócić uwagę, że sam printf jest wykonywany przez proces macierzysty, a więc w tym miejscu nie nastąpiło jeszcze zakończenie procesu macierzystego oraz nie ma gwarancji zakończenia procesu potomnego.

**Comment by ptomulik** [comment]
Fixed in #63
